### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by barf00** [chimo/gs-nodeinfo#1]
No info about how is integrated, how you will see the info, i imagine this plugin give you info about your node but not tells you where you will see that info. 

I estimated to much this kind of work, but i not happy with  those who forgot to almost say what his software do and how to use it.

Thanks you.

**Comment by chimo** [comment]
Hi,
  I've added some information about what this plugin does in the [README](https://github.com/chimo/gs-nodeinfo/blob/master/README.md).

Let me know if that helps

**Comment by chimo** [comment]
via 0a0dea42ce985c

**Comment by barf00** [comment]
Thanks you, is working
